[package]
name = "kernel"
version = "0.1.0"
authors = ["Ws12"]

[lib]
path="lib.rs"
crate-type=["staticlib"]

[dependencies]
x86="*"
linked_list_allocator={version="0.6.4",features=["use_spin"]}
spin="0.5.2"
