[package]
name = "console"
version = "0.1.0"
authors = ["Ws12"]

[dependencies]
#volatile = "0.1.0"
spin="0.4.6"
multiboot={path="../../../multiboot"}
devices={path="../../../devices"}
mem={path="../../../mem"}

[lib]
name = "console"
path = "lib.rs"
